name: Build + Deploy
on: workflow_dispatch

env:
  ITCHIO_USERNAME: edearth
  ITCHIO_GAME: malaga-jam-enero-2024
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  GODOT_VERSION: 4.2.1

jobs:
  web:
    name: Build and deploy to itch.io
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir build
          godot --export-release --headless "Web" ./build/index.html
      - name: Itch.io Deploy
        run: |
          ls ./build
          butler push ./build $ITCHIO_USERNAME/$ITCHIO_GAME:html5

